### PR TITLE
Single page app transitions

### PR DESCRIPTION
**Pull request by JakeSidSmith**
This is just an idea. I'm not sure I've fully thought through all the possible side-effects e.g. does this effect our analytics?

Please have a think about any possible ramifications of this.

The additional code required for this is less than 300kb uncompressed, so it shouldn't have a bad affect on performance.

It does however seem to work really nicely in the dev environment.

If we were to accept this, then changes will need to be made to this script if, for example, another script were added to the `head` which needs to be re-executed between pages. This may be the case for Fathom. I also notice we have a script in the footer to handle hubbub, which may need some attention.

### CODE REVIEW

**Comment by JakeSidSmith** [comment]
I have already realized one issue... links can be clicked multiple times before the new page loads.

I'll add some code later today to prevent double navigation.

**Comment by JakeSidSmith** [comment]
I could also add some nice caching and pre-requesting to this.

Essentially just store a map of ULR to Promise<HTML>.

Populate the map when the mouse enters a link, and use the existing promise result if it was recent.

**Comment by JakeSidSmith** [comment]
Have now made some improvements, but along the way I noticed I'm not currently handling reverse navigation. 😬 

So pressing the back button in your browser does nothing. 😂 Not hard to fix, just need to hook up a lil similar logic to the pop state event.

**Comment by yanneves** [comment]
This is a neat experiment but surely you agree leaving the browser to handle navigation for such low page weights is preferable for long-term maintainability? Definitely an aim to keep this repo minimalist since we can go years without changes.

**Pull request closed without merging**
